
import { CurriculumRequirement, TrainingGrade, EvidenceType, EvidenceStatus, EvidenceItem, SIA, UserProfile } from './types';

export const CURRICULUM_DATA: CurriculumRequirement[] = [
  // --- Patient Management (EPAs) based on CSV ---
  // Oculoplastics
  { specialty: "Oculoplastics", domain: "Patient Management", formType: "EPA", level: 1, requirement: "Independently perform a patient assessment and investigations sufficient to identify describe and interpret clinical findings to arrive at differential diagnoses." },
  { specialty: "Oculoplastics", domain: "Patient Management", formType: "EPA", level: 1, requirement: "Independently formulate and initiate a management plan for low complexity cases." },
  { specialty: "Oculoplastics", domain: "Patient Management", formType: "EPA", level: 1, requirement: "Justify the diagnoses and plan with reference to basic and clinical science." },
  { specialty: "Oculoplastics", domain: "Patient Management", formType: "EPA", level: 1, requirement: "Work effectively with patients and the multi-professional team." },
  { specialty: "Oculoplastics", domain: "Patient Management", formType: "EPA", level: 2, requirement: "Independently manage patients at an appropriate work-rate employing the most appropriate clinical examination equipment and investigation modalities." },
  { specialty: "Oculoplastics", domain: "Patient Management", formType: "EPA", level: 2, requirement: "Refine the differential diagnoses and management plan by application of clinical knowledge." },
  { specialty: "Oculoplastics", domain: "Patient Management", formType: "EPA", level: 3, requirement: "Independently assess and manage moderate complexity patients demonstrating an understanding of oculoplastics procedures and selecting the most appropriate treatment according to current accepted practice." },
  { specialty: "Oculoplastics", domain: "Patient Management", formType: "EPA", level: 3, requirement: "Risk assess and prioritise patients appropriately recognising the need for special interest input." },
  { specialty: "Oculoplastics", domain: "Patient Management", formType: "EPA", level: 3, requirement: "Independently perform low complexity oculoplastic procedures." },
  { specialty: "Oculoplastics", domain: "Patient Management", formType: "EPA", level: 4, requirement: "Demonstrate advanced clinical management and surgical skills." },
  { specialty: "Oculoplastics", domain: "Patient Management", formType: "EPA", level: 4, requirement: "Manage the complexity and uncertainty of oculoplastic cases." },
  { specialty: "Oculoplastics", domain: "Patient Management", formType: "EPA", level: 4, requirement: "Apply management and team working skills appropriately including in complex dynamic situations." },
  { specialty: "Oculoplastics", domain: "Patient Management", formType: "EPA", level: 4, requirement: "Be an effective supervisor teacher and trainer of oculoplastic cases." },

  // Cornea & Ocular Surface Disease
  { specialty: "Cornea & Ocular Surface Disease", domain: "Patient Management", formType: "EPA", level: 1, requirement: "Independently perform a patient assessment and investigations sufficient to identify describe and interpret clinical findings to arrive at differential diagnoses." },
  { specialty: "Cornea & Ocular Surface Disease", domain: "Patient Management", formType: "EPA", level: 1, requirement: "Independently formulate and initiate a management plan for low complexity cases." },
  { specialty: "Cornea & Ocular Surface Disease", domain: "Patient Management", formType: "EPA", level: 1, requirement: "Justify the diagnoses and plan with reference to basic and clinical science." },
  { specialty: "Cornea & Ocular Surface Disease", domain: "Patient Management", formType: "EPA", level: 1, requirement: "Work effectively with patients and the multi-professional team." },
  { specialty: "Cornea & Ocular Surface Disease", domain: "Patient Management", formType: "EPA", level: 2, requirement: "Independently manage patients at an appropriate work-rate employing the most appropriate clinical examination equipment and investigation modalities." },
  { specialty: "Cornea & Ocular Surface Disease", domain: "Patient Management", formType: "EPA", level: 2, requirement: "Refine the differential diagnoses and management plan by application of clinical knowledge." },
  { specialty: "Cornea & Ocular Surface Disease", domain: "Patient Management", formType: "EPA", level: 3, requirement: "Independently assess and manage moderate complexity patients demonstrating an understanding of cornea procedures and selecting the most appropriate treatment according to current accepted practice." },
  { specialty: "Cornea & Ocular Surface Disease", domain: "Patient Management", formType: "EPA", level: 3, requirement: "Risk assess and prioritise patients appropriately recognising the need for special interest input." },
  { specialty: "Cornea & Ocular Surface Disease", domain: "Patient Management", formType: "EPA", level: 3, requirement: "Independently perform low complexity corneal and ocular surface procedures." },
  { specialty: "Cornea & Ocular Surface Disease", domain: "Patient Management", formType: "EPA", level: 4, requirement: "Demonstrate advanced clinical management and surgical skills." },
  { specialty: "Cornea & Ocular Surface Disease", domain: "Patient Management", formType: "EPA", level: 4, requirement: "Manage the complexity and uncertainty of cornea and ocular surface disease cases." },
  { specialty: "Cornea & Ocular Surface Disease", domain: "Patient Management", formType: "EPA", level: 4, requirement: "Apply management and team working skills appropriately including in complex dynamic situations." },
  { specialty: "Cornea & Ocular Surface Disease", domain: "Patient Management", formType: "EPA", level: 4, requirement: "Be an effective supervisor teacher and trainer of cornea and ocular surface disease." },

  // Cataract Surgery
  { specialty: "Cataract Surgery", domain: "Patient Management", formType: "EPA", level: 1, requirement: "Independently perform a patient assessment and investigations sufficient to identify describe and interpret clinical findings to arrive at differential diagnoses." },
  { specialty: "Cataract Surgery", domain: "Patient Management", formType: "EPA", level: 1, requirement: "Independently formulate and initiate a management plan for low complexity cases." },
  { specialty: "Cataract Surgery", domain: "Patient Management", formType: "EPA", level: 1, requirement: "Justify the diagnoses and plan with reference to basic and clinical science." },
  { specialty: "Cataract Surgery", domain: "Patient Management", formType: "EPA", level: 1, requirement: "Work effectively with patients and the multi-professional team." },
  { specialty: "Cataract Surgery", domain: "Patient Management", formType: "EPA", level: 2, requirement: "Independently manage patients at an appropriate work-rate employing the most appropriate clinical examination equipment and investigation modalities." },
  { specialty: "Cataract Surgery", domain: "Patient Management", formType: "EPA", level: 2, requirement: "Refine the differential diagnoses and management plan by application of clinical knowledge." },
  { specialty: "Cataract Surgery", domain: "Patient Management", formType: "EPA", level: 3, requirement: "Independently assess and manage moderate complexity patients demonstrating an understanding of cataract procedures and selecting the most appropriate treatment according to current accepted practice." },
  { specialty: "Cataract Surgery", domain: "Patient Management", formType: "EPA", level: 3, requirement: "Risk assess and prioritise patients appropriately recognising the need for special interest input." },
  { specialty: "Cataract Surgery", domain: "Patient Management", formType: "EPA", level: 3, requirement: "Independently perform low risk phacoemulsification cataract procedures." },
  { specialty: "Cataract Surgery", domain: "Patient Management", formType: "EPA", level: 4, requirement: "Demonstrate advanced clinical management and surgical skills." },
  { specialty: "Cataract Surgery", domain: "Patient Management", formType: "EPA", level: 4, requirement: "Manage the complexity and uncertainty of cataract surgery cases." },
  { specialty: "Cataract Surgery", domain: "Patient Management", formType: "EPA", level: 4, requirement: "Apply management and team working skills appropriately including in complex dynamic situations." },
  { specialty: "Cataract Surgery", domain: "Patient Management", formType: "EPA", level: 4, requirement: "Be an effective supervisor teacher and trainer of cataract surgery." },

  // Glaucoma
  { specialty: "Glaucoma", domain: "Patient Management", formType: "EPA", level: 1, requirement: "Independently perform a patient assessment and investigations sufficient to identify describe and interpret clinical findings to arrive at differential diagnoses." },
  { specialty: "Glaucoma", domain: "Patient Management", formType: "EPA", level: 1, requirement: "Independently formulate and initiate a management plan for low complexity cases." },
  { specialty: "Glaucoma", domain: "Patient Management", formType: "EPA", level: 1, requirement: "Justify the diagnoses and plan with reference to basic and clinical science." },
  { specialty: "Glaucoma", domain: "Patient Management", formType: "EPA", level: 1, requirement: "Work effectively with patients and the multi-professional team." },
  { specialty: "Glaucoma", domain: "Patient Management", formType: "EPA", level: 2, requirement: "Independently manage patients at an appropriate work-rate employing the most appropriate clinical examination equipment and investigation modalities." },
  { specialty: "Glaucoma", domain: "Patient Management", formType: "EPA", level: 2, requirement: "Refine the differential diagnoses and management plan by application of clinical knowledge." },
  { specialty: "Glaucoma", domain: "Patient Management", formType: "EPA", level: 3, requirement: "Independently assess and manage moderate complexity patients demonstrating an understanding of glaucoma procedures and selecting the most appropriate treatment according to current accepted practice." },
  { specialty: "Glaucoma", domain: "Patient Management", formType: "EPA", level: 3, requirement: "Risk assess and prioritise patients appropriately recognising the need for special interest input." },
  { specialty: "Glaucoma", domain: "Patient Management", formType: "EPA", level: 3, requirement: "Independently perform low complexity glaucoma procedures." },
  { specialty: "Glaucoma", domain: "Patient Management", formType: "EPA", level: 4, requirement: "Demonstrate advanced clinical management and surgical skills." },
  { specialty: "Glaucoma", domain: "Patient Management", formType: "EPA", level: 4, requirement: "Manage the complexity and uncertainty of glaucoma cases." },
  { specialty: "Glaucoma", domain: "Patient Management", formType: "EPA", level: 4, requirement: "Apply management and team working skills appropriately including in complex dynamic situations." },
  { specialty: "Glaucoma", domain: "Patient Management", formType: "EPA", level: 4, requirement: "Be an effective supervisor teacher and trainer of glaucoma conditions." },

  // Uveitis
  { specialty: "Uveitis", domain: "Patient Management", formType: "EPA", level: 1, requirement: "Independently perform a patient assessment and investigations sufficient to identify describe and interpret clinical findings to arrive at differential diagnoses." },
  { specialty: "Uveitis", domain: "Patient Management", formType: "EPA", level: 1, requirement: "Independently formulate and initiate a management plan for low complexity cases." },
  { specialty: "Uveitis", domain: "Patient Management", formType: "EPA", level: 1, requirement: "Justify the diagnoses and plan with reference to basic and clinical science." },
  { specialty: "Uveitis", domain: "Patient Management", formType: "EPA", level: 1, requirement: "Work effectively with patients and the multi-professional team." },
  { specialty: "Uveitis", domain: "Patient Management", formType: "EPA", level: 2, requirement: "Independently manage patients at an appropriate work-rate employing the most appropriate clinical examination equipment and investigation modalities." },
  { specialty: "Uveitis", domain: "Patient Management", formType: "EPA", level: 2, requirement: "Refine the differential diagnoses and management plan by application of clinical knowledge." },
  { specialty: "Uveitis", domain: "Patient Management", formType: "EPA", level: 3, requirement: "Independently assess and manage moderate complexity patients demonstrating an understanding of practical and surgical procedures used in the setting of uveitis and selecting the most appropriate treatment according to current accepted practice." },
  { specialty: "Uveitis", domain: "Patient Management", formType: "EPA", level: 3, requirement: "Risk assess and prioritise patients appropriately recognising the need for special interest input." },
  { specialty: "Uveitis", domain: "Patient Management", formType: "EPA", level: 3, requirement: "Independently perform low complexity procedures for the uveitic patient." },
  { specialty: "Uveitis", domain: "Patient Management", formType: "EPA", level: 4, requirement: "Demonstrate advanced clinical management and surgical skills." },
  { specialty: "Uveitis", domain: "Patient Management", formType: "EPA", level: 4, requirement: "Manage the complexity and uncertainty of uveitis disease cases." },
  { specialty: "Uveitis", domain: "Patient Management", formType: "EPA", level: 4, requirement: "Apply management and team working skills appropriately including in complex dynamic situations." },
  { specialty: "Uveitis", domain: "Patient Management", formType: "EPA", level: 4, requirement: "Be an effective supervisor teacher and trainer of uveitis disease." },

  // Medical Retina
  { specialty: "Medical Retina", domain: "Patient Management", formType: "EPA", level: 1, requirement: "Independently perform a patient assessment and investigations sufficient to identify describe and interpret clinical findings to arrive at differential diagnoses." },
  { specialty: "Medical Retina", domain: "Patient Management", formType: "EPA", level: 1, requirement: "Independently formulate and initiate a management plan for low complexity cases." },
  { specialty: "Medical Retina", domain: "Patient Management", formType: "EPA", level: 1, requirement: "Justify the diagnoses and plan with reference to basic and clinical science." },
  { specialty: "Medical Retina", domain: "Patient Management", formType: "EPA", level: 1, requirement: "Work effectively with patients and the multi-professional team." },
  { specialty: "Medical Retina", domain: "Patient Management", formType: "EPA", level: 2, requirement: "Independently manage patients at an appropriate work-rate employing the most appropriate clinical examination equipment and investigation modalities." },
  { specialty: "Medical Retina", domain: "Patient Management", formType: "EPA", level: 2, requirement: "Refine the differential diagnoses and management plan by application of clinical knowledge." },
  { specialty: "Medical Retina", domain: "Patient Management", formType: "EPA", level: 3, requirement: "Independently assess and manage moderate complexity patients demonstrating an understanding of medical retina procedures and selecting the most appropriate treatment according to current accepted practice." },
  { specialty: "Medical Retina", domain: "Patient Management", formType: "EPA", level: 3, requirement: "Risk assess and prioritise patients appropriately recognising the need for special interest input." },
  { specialty: "Medical Retina", domain: "Patient Management", formType: "EPA", level: 3, requirement: "Independently perform low complexity medical retina procedures." },
  { specialty: "Medical Retina", domain: "Patient Management", formType: "EPA", level: 4, requirement: "Demonstrate advanced clinical management and practical skills." },
  { specialty: "Medical Retina", domain: "Patient Management", formType: "EPA", level: 4, requirement: "Manage the complexity and uncertainty of medical retina disease cases." },
  { specialty: "Medical Retina", domain: "Patient Management", formType: "EPA", level: 4, requirement: "Apply management and team working skills appropriately including in complex dynamic situations." },
  { specialty: "Medical Retina", domain: "Patient Management", formType: "EPA", level: 4, requirement: "Be an effective supervisor teacher and trainer of medical retina disease." },

  // Vitreoretinal Surgery
  { specialty: "Vitreoretinal Surgery", domain: "Patient Management", formType: "EPA", level: 1, requirement: "Independently perform a patient assessment and investigations sufficient to identify describe and interpret clinical findings to arrive at differential diagnoses." },
  { specialty: "Vitreoretinal Surgery", domain: "Patient Management", formType: "EPA", level: 1, requirement: "Independently formulate and initiate a management plan for low complexity cases." },
  { specialty: "Vitreoretinal Surgery", domain: "Patient Management", formType: "EPA", level: 1, requirement: "Justify the diagnoses and plan with reference to basic and clinical science." },
  { specialty: "Vitreoretinal Surgery", domain: "Patient Management", formType: "EPA", level: 1, requirement: "Work effectively with patients and the multi-professional team." },
  { specialty: "Vitreoretinal Surgery", domain: "Patient Management", formType: "EPA", level: 2, requirement: "Independently manage patients at an appropriate work-rate employing the most appropriate clinical examination equipment and investigation modalities." },
  { specialty: "Vitreoretinal Surgery", domain: "Patient Management", formType: "EPA", level: 2, requirement: "Refine the differential diagnoses and management plan by application of clinical knowledge." },
  { specialty: "Vitreoretinal Surgery", domain: "Patient Management", formType: "EPA", level: 3, requirement: "Independently assess and manage moderate complexity patients demonstrating an understanding of vitreoretinal procedures and selecting the most appropriate treatment according to current accepted practice." },
  { specialty: "Vitreoretinal Surgery", domain: "Patient Management", formType: "EPA", level: 3, requirement: "Risk assess and prioritise patients appropriately recognising the need for special interest input." },
  { specialty: "Vitreoretinal Surgery", domain: "Patient Management", formType: "EPA", level: 3, requirement: "Independently perform low complexity vitreoretinal procedures." },
  { specialty: "Vitreoretinal Surgery", domain: "Patient Management", formType: "EPA", level: 4, requirement: "Demonstrate advanced clinical management and surgical skills." },
  { specialty: "Vitreoretinal Surgery", domain: "Patient Management", formType: "EPA", level: 4, requirement: "Manage the complexity and uncertainty of vitreoretinal disease cases." },
  { specialty: "Vitreoretinal Surgery", domain: "Patient Management", formType: "EPA", level: 4, requirement: "Apply management and team working skills appropriately including in complex dynamic situations." },
  { specialty: "Vitreoretinal Surgery", domain: "Patient Management", formType: "EPA", level: 4, requirement: "Be an effective supervisor teacher and trainer of vitreoretinal disease." },

  // Ocular Motility
  { specialty: "Ocular Motility", domain: "Patient Management", formType: "EPA", level: 1, requirement: "Independently perform a patient assessment and investigations sufficient to identify describe and interpret clinical findings to arrive at differential diagnoses." },
  { specialty: "Ocular Motility", domain: "Patient Management", formType: "EPA", level: 1, requirement: "Independently formulate and initiate a management plan for low complexity cases." },
  { specialty: "Ocular Motility", domain: "Patient Management", formType: "EPA", level: 1, requirement: "Justify the diagnoses and plan with reference to basic and clinical science." },
  { specialty: "Ocular Motility", domain: "Patient Management", formType: "EPA", level: 1, requirement: "Work effectively with patients and the multi-professional team." },
  { specialty: "Ocular Motility", domain: "Patient Management", formType: "EPA", level: 2, requirement: "Independently manage patients at an appropriate work-rate employing the most appropriate clinical examination equipment and investigation modalities." },
  { specialty: "Ocular Motility", domain: "Patient Management", formType: "EPA", level: 2, requirement: "Refine the differential diagnoses and management plan by application of clinical knowledge." },
  { specialty: "Ocular Motility", domain: "Patient Management", formType: "EPA", level: 3, requirement: "Independently assess and manage moderate complexity patients demonstrating an understanding of ocular motility procedures and selecting the most appropriate treatment according to current accepted practice." },
  { specialty: "Ocular Motility", domain: "Patient Management", formType: "EPA", level: 3, requirement: "Risk assess and prioritise patients appropriately recognising the need for special interest input." },
  { specialty: "Ocular Motility", domain: "Patient Management", formType: "EPA", level: 3, requirement: "Independently perform low complexity muscle surgery." },
  { specialty: "Ocular Motility", domain: "Patient Management", formType: "EPA", level: 4, requirement: "Demonstrate advanced clinical management and surgical skills." },
  { specialty: "Ocular Motility", domain: "Patient Management", formType: "EPA", level: 4, requirement: "Manage the complexity and uncertainty of ocular motility cases." },
  { specialty: "Ocular Motility", domain: "Patient Management", formType: "EPA", level: 4, requirement: "Apply management and team working skills appropriately including in complex dynamic situations." },
  { specialty: "Ocular Motility", domain: "Patient Management", formType: "EPA", level: 4, requirement: "Be an effective supervisor teacher and trainer of ocular motility cases." },

  // Neuro-Ophthalmology
  { specialty: "Neuro-Ophthalmology", domain: "Patient Management", formType: "EPA", level: 1, requirement: "Independently perform a patient assessment and investigations sufficient to identify describe and interpret clinical findings to arrive at differential diagnoses." },
  { specialty: "Neuro-Ophthalmology", domain: "Patient Management", formType: "EPA", level: 1, requirement: "Independently formulate and initiate a management plan for low complexity cases." },
  { specialty: "Neuro-Ophthalmology", domain: "Patient Management", formType: "EPA", level: 1, requirement: "Justify the diagnoses and plan with reference to basic and clinical science." },
  { specialty: "Neuro-Ophthalmology", domain: "Patient Management", formType: "EPA", level: 1, requirement: "Work effectively with patients and the multi-professional team." },
  { specialty: "Neuro-Ophthalmology", domain: "Patient Management", formType: "EPA", level: 2, requirement: "Independently manage patients at an appropriate work-rate employing the most appropriate clinical examination equipment and investigation modalities." },
  { specialty: "Neuro-Ophthalmology", domain: "Patient Management", formType: "EPA", level: 2, requirement: "Refine the differential diagnoses and management plan by application of clinical knowledge." },
  { specialty: "Neuro-Ophthalmology", domain: "Patient Management", formType: "EPA", level: 3, requirement: "Independently assess and manage moderate complexity patients demonstrating an understanding of neuro-ophthalmology procedures and selecting the most appropriate treatment according to current accepted practice." },
  { specialty: "Neuro-Ophthalmology", domain: "Patient Management", formType: "EPA", level: 3, requirement: "Risk assess and prioritise patients appropriately recognising the need for special interest input." },
  { specialty: "Neuro-Ophthalmology", domain: "Patient Management", formType: "EPA", level: 3, requirement: "Independently perform low complexity neuro-ophthalmology procedures." },
  { specialty: "Neuro-Ophthalmology", domain: "Patient Management", formType: "EPA", level: 4, requirement: "Demonstrate advanced clinical management and surgical skills." },
  { specialty: "Neuro-Ophthalmology", domain: "Patient Management", formType: "EPA", level: 4, requirement: "Manage the complexity and uncertainty of neuro-ophthalmology cases." },
  { specialty: "Neuro-Ophthalmology", domain: "Patient Management", formType: "EPA", level: 4, requirement: "Apply management and team working skills appropriately including in complex dynamic situations." },
  { specialty: "Neuro-Ophthalmology", domain: "Patient Management", formType: "EPA", level: 4, requirement: "Be an effective supervisor teacher and trainer of neuro-ophthalmology cases." },

  // Paediatric Ophthalmology
  { specialty: "Paediatric Ophthalmology", domain: "Patient Management", formType: "EPA", level: 1, requirement: "Independently perform an age-appropriate patient assessment and investigation sufficient to identify describe and interpret clinical findings to arrive at differential diagnoses." },
  { specialty: "Paediatric Ophthalmology", domain: "Patient Management", formType: "EPA", level: 1, requirement: "Independently formulate and initiate a management plan for low complexity cases." },
  { specialty: "Paediatric Ophthalmology", domain: "Patient Management", formType: "EPA", level: 1, requirement: "Justify the diagnoses and plan with reference to basic and clinical science." },
  { specialty: "Paediatric Ophthalmology", domain: "Patient Management", formType: "EPA", level: 1, requirement: "Work effectively with patients and the multi-professional team." },
  { specialty: "Paediatric Ophthalmology", domain: "Patient Management", formType: "EPA", level: 2, requirement: "Independently manage patients at an appropriate work-rate employing the most appropriate clinical examination equipment and investigation modalities." },
  { specialty: "Paediatric Ophthalmology", domain: "Patient Management", formType: "EPA", level: 2, requirement: "Refine the differential diagnoses and management plan by application of clinical knowledge." },
  { specialty: "Paediatric Ophthalmology", domain: "Patient Management", formType: "EPA", level: 3, requirement: "Independently assess and manage moderate complexity patients demonstrating an understanding of procedures for paediatric conditions and selecting the most appropriate treatment according to current accepted practice." },
  { specialty: "Paediatric Ophthalmology", domain: "Patient Management", formType: "EPA", level: 3, requirement: "Risk assess and prioritise patients appropriately recognising the need for special interest input." },
  { specialty: "Paediatric Ophthalmology", domain: "Patient Management", formType: "EPA", level: 3, requirement: "Independently perform low complexity extraocular paediatric procedures." },
  { specialty: "Paediatric Ophthalmology", domain: "Patient Management", formType: "EPA", level: 4, requirement: "Demonstrate advanced clinical management and surgical skills." },
  { specialty: "Paediatric Ophthalmology", domain: "Patient Management", formType: "EPA", level: 4, requirement: "Manage the complexity and uncertainty of paediatric ophthalmology cases." },
  { specialty: "Paediatric Ophthalmology", domain: "Patient Management", formType: "EPA", level: 4, requirement: "Apply management and team working skills appropriately including in complex dynamic situations." },
  { specialty: "Paediatric Ophthalmology", domain: "Patient Management", formType: "EPA", level: 4, requirement: "Be an effective supervisor teacher and trainer of paediatric ophthalmology." },

  // Urgent Eye Care
  { specialty: "Urgent Eye Care", domain: "Patient Management", formType: "EPA", level: 1, requirement: "Independently perform a patient assessment and investigations sufficient to identify describe and interpret clinical findings to arrive at differential diagnoses." },
  { specialty: "Urgent Eye Care", domain: "Patient Management", formType: "EPA", level: 1, requirement: "Independently formulate and initiate a management plan for low complexity cases." },
  { specialty: "Urgent Eye Care", domain: "Patient Management", formType: "EPA", level: 1, requirement: "Justify the diagnoses and plan with reference to basic and clinical science." },
  { specialty: "Urgent Eye Care", domain: "Patient Management", formType: "EPA", level: 1, requirement: "Work effectively with patients and the multi-professional team." },
  { specialty: "Urgent Eye Care", domain: "Patient Management", formType: "EPA", level: 2, requirement: "Independently manage patients at an appropriate work-rate employing the most appropriate clinical examination equipment and investigation modalities." },
  { specialty: "Urgent Eye Care", domain: "Patient Management", formType: "EPA", level: 2, requirement: "Refine the differential diagnoses and management plan by application of clinical knowledge." },
  { specialty: "Urgent Eye Care", domain: "Patient Management", formType: "EPA", level: 3, requirement: "Independently assess and manage moderate complexity patients demonstrating an understanding of urgent eye care procedures and selecting the most appropriate treatment according to current accepted practice." },
  { specialty: "Urgent Eye Care", domain: "Patient Management", formType: "EPA", level: 3, requirement: "Risk assess and prioritise patients appropriately recognising the need for special interest input." },
  { specialty: "Urgent Eye Care", domain: "Patient Management", formType: "EPA", level: 3, requirement: "Independently perform surgery requiring immediate intervention." },
  { specialty: "Urgent Eye Care", domain: "Patient Management", formType: "EPA", level: 4, requirement: "Demonstrate advanced clinical management and surgical skills." },
  { specialty: "Urgent Eye Care", domain: "Patient Management", formType: "EPA", level: 4, requirement: "Manage the complexity and uncertainty of urgent eye care." },
  { specialty: "Urgent Eye Care", domain: "Patient Management", formType: "EPA", level: 4, requirement: "Apply management and team working skills appropriately including in complex dynamic situations." },
  { specialty: "Urgent Eye Care", domain: "Patient Management", formType: "EPA", level: 4, requirement: "Be an effective supervisor teacher and trainer of urgent eye care." },

  // Community Ophthalmology
  { specialty: "Community Ophthalmology", domain: "Patient Management", formType: "EPA", level: 1, requirement: "Understand the role of a Community Ophthalmology Service." },
  { specialty: "Community Ophthalmology", domain: "Patient Management", formType: "EPA", level: 1, requirement: "Communicate and deliver feedback to referrers and patients to support integrated care." },
  { specialty: "Community Ophthalmology", domain: "Patient Management", formType: "EPA", level: 2, requirement: "Be aware of common public health issues and requirements specific to ophthalmology." },
  { specialty: "Community Ophthalmology", domain: "Patient Management", formType: "EPA", level: 2, requirement: "Understand the environmental impact of eye health care." },
  { specialty: "Community Ophthalmology", domain: "Patient Management", formType: "EPA", level: 3, requirement: "Understand the provision of community ophthalmology and screening programmes." },
  { specialty: "Community Ophthalmology", domain: "Patient Management", formType: "EPA", level: 3, requirement: "Understand the epidemiology of eye disease and visual impairment and public health approaches to blindness prevention." },
  { specialty: "Community Ophthalmology", domain: "Patient Management", formType: "EPA", level: 3, requirement: "Understand the role of commissioning in eye health care." },
  { specialty: "Community Ophthalmology", domain: "Patient Management", formType: "EPA", level: 3, requirement: "Evaluate design and delivery of care pathways." },
  { specialty: "Community Ophthalmology", domain: "Patient Management", formType: "EPA", level: 3, requirement: "Demonstrate skills to assess and assure high quality outcomes in Community Ophthalmology Services." },
  { specialty: "Community Ophthalmology", domain: "Patient Management", formType: "EPA", level: 4, requirement: "Demonstrate advanced skills necessary to assess the eye health needs of a population and analyse local priorities." },
  { specialty: "Community Ophthalmology", domain: "Patient Management", formType: "EPA", level: 4, requirement: "Be an effective clinical leader supervisor and trainer of the multi-disciplinary team." },

  // --- Non-patient Management (GSAT) based on text ---
  // Research and Scholarship
  { specialty: "Research and Scholarship", domain: "Non-patient Management", formType: "GSAT", level: 1, requirement: "Adopt an evidence‑based approach to clinical practice." },
  { specialty: "Research and Scholarship", domain: "Non-patient Management", formType: "GSAT", level: 2, requirement: "Implement an evidence‑based approach to shared decision making and enhancing patient outcomes." },
  { specialty: "Research and Scholarship", domain: "Non-patient Management", formType: "GSAT", level: 2, requirement: "Implement service improvement by revising and developing guidelines, treatments and practical procedures using current clinical research and contemporary evidence." },
  { specialty: "Research and Scholarship", domain: "Non-patient Management", formType: "GSAT", level: 3, requirement: "Understand the principles of research methods, research governance, application of ethics to research and the translation of research into practice." },
  { specialty: "Research and Scholarship", domain: "Non-patient Management", formType: "GSAT", level: 3, requirement: "Critically appraise existing published research." },
  { specialty: "Research and Scholarship", domain: "Non-patient Management", formType: "GSAT", level: 3, requirement: "Understand research and deliver oral presentations." },
  { specialty: "Research and Scholarship", domain: "Non-patient Management", formType: "GSAT", level: 4, requirement: "Demonstrate competencies for commencing clinical research." },
  { specialty: "Research and Scholarship", domain: "Non-patient Management", formType: "GSAT", level: 4, requirement: "Understand research, deliver poster presentations and improve oral presenting." },
  { specialty: "Research and Scholarship", domain: "Non-patient Management", formType: "GSAT", level: 4, requirement: "Promote innovation in ophthalmology." },

  // Education and Training
  { specialty: "Education and Training", domain: "Non-patient Management", formType: "GSAT", level: 1, requirement: "Ensure patient safety is paramount in all training and learning events." },
  { specialty: "Education and Training", domain: "Non-patient Management", formType: "GSAT", level: 1, requirement: "Actively participate in own induction and training." },
  { specialty: "Education and Training", domain: "Non-patient Management", formType: "GSAT", level: 1, requirement: "Deliver teaching activities under guidance." },
  { specialty: "Education and Training", domain: "Non-patient Management", formType: "GSAT", level: 1, requirement: "Deliver patient education." },
  { specialty: "Education and Training", domain: "Non-patient Management", formType: "GSAT", level: 2, requirement: "Plan and provide education and training activities for medical trainees and other professionals." },
  { specialty: "Education and Training", domain: "Non-patient Management", formType: "GSAT", level: 2, requirement: "Give constructive feedback on learning activities." },
  { specialty: "Education and Training", domain: "Non-patient Management", formType: "GSAT", level: 3, requirement: "Create learning opportunities for others." },
  { specialty: "Education and Training", domain: "Non-patient Management", formType: "GSAT", level: 3, requirement: "Provide objective assessment." },
  { specialty: "Education and Training", domain: "Non-patient Management", formType: "GSAT", level: 3, requirement: "Design and contribute to patient education." },
  { specialty: "Education and Training", domain: "Non-patient Management", formType: "GSAT", level: 4, requirement: "Demonstrate readiness to act as a clinical and educational trainer." },
  { specialty: "Education and Training", domain: "Non-patient Management", formType: "GSAT", level: 4, requirement: "Balance service and training needs." },
  { specialty: "Education and Training", domain: "Non-patient Management", formType: "GSAT", level: 4, requirement: "Be able to identify and support a trainee experiencing difficulty." },

  // Safeguarding and Holistic Patient Care
  { specialty: "Safeguarding and Holistic Patient Care", domain: "Non-patient Management", formType: "GSAT", level: 1, requirement: "Understand and promote professional responsibility of safeguarding." },
  { specialty: "Safeguarding and Holistic Patient Care", domain: "Non-patient Management", formType: "GSAT", level: 1, requirement: "Demonstrate familiarity with local safeguarding procedures and contacts." },
  { specialty: "Safeguarding and Holistic Patient Care", domain: "Non-patient Management", formType: "GSAT", level: 1, requirement: "Demonstrate awareness of possibility of non‑accidental injury in vulnerable patients." },
  { specialty: "Safeguarding and Holistic Patient Care", domain: "Non-patient Management", formType: "GSAT", level: 1, requirement: "Document safeguarding concerns accurately and refer to senior staff." },
  { specialty: "Safeguarding and Holistic Patient Care", domain: "Non-patient Management", formType: "GSAT", level: 2, requirement: "Recognise where specialised management techniques may be necessary for those with special needs." },
  { specialty: "Safeguarding and Holistic Patient Care", domain: "Non-patient Management", formType: "GSAT", level: 3, requirement: "Take responsibility for safeguarding of children and vulnerable adults, referring and taking appropriate action." },
  { specialty: "Safeguarding and Holistic Patient Care", domain: "Non-patient Management", formType: "GSAT", level: 3, requirement: "Apply mental capacity legislation in clinical practice." },
  { specialty: "Safeguarding and Holistic Patient Care", domain: "Non-patient Management", formType: "GSAT", level: 3, requirement: "Apply appropriate equality and diversity legislation in clinical practice." },
  { specialty: "Safeguarding and Holistic Patient Care", domain: "Non-patient Management", formType: "GSAT", level: 4, requirement: "Critically evaluate personal and wider organisational responses to safeguarding issues." },
  { specialty: "Safeguarding and Holistic Patient Care", domain: "Non-patient Management", formType: "GSAT", level: 4, requirement: "Supervise and support other professionals with regard to safeguarding." },
  { specialty: "Safeguarding and Holistic Patient Care", domain: "Non-patient Management", formType: "GSAT", level: 4, requirement: "Demonstrate effective specialised management techniques for those with special needs." },

  // Patient Safety and Quality Improvement
  { specialty: "Patient Safety and Quality Improvement", domain: "Non-patient Management", formType: "GSAT", level: 1, requirement: "Know the principles, recognise the contribution to improved practice and take part in clinical governance, audit and quality improvement activities." },
  { specialty: "Patient Safety and Quality Improvement", domain: "Non-patient Management", formType: "GSAT", level: 1, requirement: "Identify appropriate information from a variety of data sources." },
  { specialty: "Patient Safety and Quality Improvement", domain: "Non-patient Management", formType: "GSAT", level: 2, requirement: "Apply clear and appropriate clinical reasoning to make safe decisions." },
  { specialty: "Patient Safety and Quality Improvement", domain: "Non-patient Management", formType: "GSAT", level: 2, requirement: "Practice in line with latest evidence." },
  { specialty: "Patient Safety and Quality Improvement", domain: "Non-patient Management", formType: "GSAT", level: 2, requirement: "Maintain appropriate audits of practice." },
  { specialty: "Patient Safety and Quality Improvement", domain: "Non-patient Management", formType: "GSAT", level: 3, requirement: "Apply quality improvement methods." },
  { specialty: "Patient Safety and Quality Improvement", domain: "Non-patient Management", formType: "GSAT", level: 3, requirement: "Design and implement quality improvement programmes to improve clinical effectiveness, patient safety and patient experience." },
  { specialty: "Patient Safety and Quality Improvement", domain: "Non-patient Management", formType: "GSAT", level: 3, requirement: "Analyse and critique published research." },
  { specialty: "Patient Safety and Quality Improvement", domain: "Non-patient Management", formType: "GSAT", level: 4, requirement: "Share improved practice with others and be able to justify changes made." },
  { specialty: "Patient Safety and Quality Improvement", domain: "Non-patient Management", formType: "GSAT", level: 4, requirement: "Critically evaluate own skills in quality improvement." },
  { specialty: "Patient Safety and Quality Improvement", domain: "Non-patient Management", formType: "GSAT", level: 4, requirement: "Promote clinical governance and quality improvement in the wider organisation / NHS." },

  // Leadership and Team Working
  { specialty: "Leadership and Team Working", domain: "Non-patient Management", formType: "GSAT", level: 1, requirement: "Know about leadership competencies in the nine behavioural dimensions defined by the NHS Leadership Academy (e.g. inspiring shared purpose, leading with care, engaging the team)." },
  { specialty: "Leadership and Team Working", domain: "Non-patient Management", formType: "GSAT", level: 1, requirement: "Know the principles of leadership and identify areas for own development." },
  { specialty: "Leadership and Team Working", domain: "Non-patient Management", formType: "GSAT", level: 2, requirement: "Document and evidence leadership behaviours." },
  { specialty: "Leadership and Team Working", domain: "Non-patient Management", formType: "GSAT", level: 2, requirement: "Practice within a multidisciplinary team to develop leadership projects." },
  { specialty: "Leadership and Team Working", domain: "Non-patient Management", formType: "GSAT", level: 3, requirement: "Demonstrate the authority, capacity and motivation to implement change." },
  { specialty: "Leadership and Team Working", domain: "Non-patient Management", formType: "GSAT", level: 3, requirement: "Design own projects related to leadership and management with predetermined outcomes and reflect on success." },
  { specialty: "Leadership and Team Working", domain: "Non-patient Management", formType: "GSAT", level: 4, requirement: "Critically evaluate own skills in leadership with particular reference to the quality of patient care." },
  { specialty: "Leadership and Team Working", domain: "Non-patient Management", formType: "GSAT", level: 4, requirement: "Promote service improvement through quality, innovation, productivity and prevention; supervision of the multidisciplinary team; and effective management of incidents and complaints." },

  // Health Promotion
  { specialty: "Health Promotion", domain: "Non-patient Management", formType: "GSAT", level: 1, requirement: "Provide appropriate lifestyle advice." },
  { specialty: "Health Promotion", domain: "Non-patient Management", formType: "GSAT", level: 1, requirement: "Adopt local and national guidelines on prevention of infection." },
  { specialty: "Health Promotion", domain: "Non-patient Management", formType: "GSAT", level: 1, requirement: "Advise appropriately about the systemic side‑effects of drugs." },
  { specialty: "Health Promotion", domain: "Non-patient Management", formType: "GSAT", level: 1, requirement: "Know the principles of screening." },
  { specialty: "Health Promotion", domain: "Non-patient Management", formType: "GSAT", level: 1, requirement: "Use and promote means of eye injury protection." },
  { specialty: "Health Promotion", domain: "Non-patient Management", formType: "GSAT", level: 2, requirement: "Be aware of and respect the impact of social, economic, cultural and religious factors on health." },
  { specialty: "Health Promotion", domain: "Non-patient Management", formType: "GSAT", level: 2, requirement: "Have detailed knowledge of national screening programmes, especially for ophthalmic diseases." },
  { specialty: "Health Promotion", domain: "Non-patient Management", formType: "GSAT", level: 3, requirement: "Demonstrate leadership in the promotion of eye and general health in the wider community." },
  { specialty: "Health Promotion", domain: "Non-patient Management", formType: "GSAT", level: 3, requirement: "Promote immunisation." },
  { specialty: "Health Promotion", domain: "Non-patient Management", formType: "GSAT", level: 3, requirement: "Develop special‑interest‑area‑specific guidance for health promotion." },
  { specialty: "Health Promotion", domain: "Non-patient Management", formType: "GSAT", level: 4, requirement: "Be an effective supervisor and leader in the area of health promotion." },
];

export const INITIAL_PROFILE: UserProfile = {
  name: "Dr. Alex Carter",
  grade: TrainingGrade.ST4,
  location: "London Deanery",
  fte: 100,
  arcpMonth: "June",
  cctDate: "2027-08-01",
  supervisorName: "Mr. James Wright",
  supervisorEmail: "j.wright@nhs.net",
  predictedSIAs: ["Oculoplastics", "Ocular Motility"],
  pdpGoals: []
};

export const INITIAL_SIAS: SIA[] = [
  { id: '1', specialty: "Oculoplastics", level: 2, supervisorInitials: "JW" },
  { id: '2', specialty: "Medical Retina", level: 3, supervisorInitials: "SR" },
  { id: '3', specialty: "Cataract Surgery", level: 4, supervisorInitials: "AL" },
];

export const INITIAL_EVIDENCE: EvidenceItem[] = [
  { id: 'ev1', type: EvidenceType.CbD, title: "Ptosis management case study", sia: "Oculoplastics", level: 2, date: "2024-03-15", status: EvidenceStatus.SignedOff },
  { id: 'ev2', type: EvidenceType.DOPs, title: "Basal cell carcinoma excision", sia: "Oculoplastics", level: 2, date: "2024-03-20", status: EvidenceStatus.Submitted },
  { id: 'ev3', type: EvidenceType.Reflection, title: "Clinic communication reflection", date: "2024-03-22", status: EvidenceStatus.Draft },
];

export const SPECIALTIES = [
  "Oculoplastics", "Cornea & Ocular Surface Disease", "Cataract Surgery", "Glaucoma", "Uveitis",
  "Medical Retina", "Vitreoretinal Surgery", "Ocular Motility", "Neuro-Ophthalmology",
  "Paediatric Ophthalmology", "Urgent Eye Care", "Community Ophthalmology"
];
